= Glosara to-do list
:author: Marcos Cruz (programandala.net)
:revdate: 2020-04-07

== 2017-02-15

Make the delimiters configurable with a command line option.

== 2017-02-15

Add `--mode` option to select "glossary" or "module".

The module mode creates a list of modules (files) that contain a list
of entry names each.

== 2017-02-15

Add an option to link the glossary entry to the file it was extracted
from.

== 2017-07-14

Fix `input-option`.

== 2017-10-21

Make `max-word-length` configurable.

== 2017-11-19

Add an option to use a prefix for link anchors. This way different
glossaries with homonimous could be built apart and then combined into
one single manual.

== 2018-04-17

Combine `--annex` with the planned `--mode` option.

== 2018-04-17

Check if it's useful to create explicit links with `--annex`, or
implicit links is enough.

== 2018-04-17

Enable several `--output`. Just change the current one.

== 2018-04-18

Check explicit links.

== 2018-04-18

Use Gforth's `save-mem` or Galope's `>stringer`, not both of them.

== 2020-04-07

Add an option to create glossary sections, by initial.

Fix: `previous-initial` changes without reason.
