= Glosara to-do list
:author: Marcos Cruz (programandala.net)
:revdate: 2020-05-13

== 2017-02-15

Add `--mode` option to select "glossary" or "module".

The module mode creates a list of modules (files) that contain a list
of entry names each.

== 2017-02-15

Add an option to link the glossary entry to the file it was extracted
from.

== 2017-10-21

Make `max-word-length` configurable.

== 2017-11-19

Add an option to use a prefix for link anchors. This way different
glossaries with homonims could be built apart and then combined into
one single manual.

== 2018-04-17

Combine `--annex` with the planned `--mode` option.

== 2018-04-17

Check if it's useful to create explicit links with `--annex`, or
implicit links is enough.

== 2018-04-17

Enable several `--output`. Just change the current one.

== 2018-04-18

Check explicit links.

== 2020-04-12

Idea: Run the conversion after parsing all options, instead of doing
it in `option` (by calling `input-file` or `input-option`). Now the
problem is the order matters, e.g. "--dir" only works if followed by
"--input" or an input file. But the advantage of the current method is
several inputs can be processed.

== 2020-05-06

Change the location of `preserve-double-backticks`
`restore-double-backticks` and `finish-links` in order to make lower
level words independent, easier to test.

== 2020-05-12

In verbose mode, display the homonyms (entry name and source file).

== 2020-05-13

Confirm this problem in Solo Forth:

This explicit link is ignored:

----
  \ | `<<src-lib-prog-editor-specforth-fs, b>>` ``( -- )``
  \ | Used after `<<src-lib-prog-editor-specforth-fs, f>>` to
  \ backup the cursor by the length of the most recent text.
----

But this way it works:

----
  \ | `<<src-lib-prog-editor-specforth-fs, b>>`
  \ ``( -- )``
  \ | Used after `<<src-lib-prog-editor-specforth-fs, f>>` to
  \ backup the cursor by the length of the most recent text.
----
